name: Create release and publish to NPM

on:
  push:
    branches:
      - main
    paths-ignore:
      - .eslintrc
      - .github/**/*

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: myparcelnl/actions/yarn-install@v2

      - name: Run semantic release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
