name: Create release and publish to NPM

on:
  push:
    branches:
      - master
    paths-ignore:
      - .eslintrc
      - .github/**/*

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci

      - name: Run semantic release
        uses: brpaz/action-semantic-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
